src/Entity/Comment.php
<?php

namespace App\Entity;

use App\Repository\CommentRepository;
use Doctrine\ORM\Mapping as ORM;
use JsonSerializable;

/**
 * @ORM\Entity(repositoryClass=CommentRepository::class)
 */
class Comment implements JsonSerializable
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="comments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    private $authorIconPAth;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_date;

    /**
     * @ORM\ManyToOne(targetEntity=Trick::class, inversedBy="comments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $trick;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getAuthorIconPath(): ?string
    {
        return $this->authorIconPAth;
    }

    public function setAuthorIconPAth(string $path)
    {
        $this->authorIconPAth = $path;

        return $this;
    }

    public function getCreatedDate(): ?\DateTimeInterface
    {
        return $this->created_date;
    }

    public function setCreatedDate(\DateTimeInterface $created_date): self
    {
        $this->created_date = $created_date;

        return $this;
    }

    public function getTrick(): ?Trick
    {
        return $this->trick;
    }

    public function setTrick(?Trick $trick): self
    {
        $this->trick = $trick;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function jsonSerialize()
    {
        return
            [
                'id'   => $this->getId(),
                'author' => $this->getAuthor(),
                'created_date' => $this->getCreatedDate(),
                'trick' => $this->getTrick(),
                'content' => $this->getContent(),
                'authorIconPAth' => $this->getAuthorIconPath()
            ];
    }
}

src/Entity/Trick.php
<?php

namespace App\Entity;

use App\Repository\TrickRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use JsonSerializable;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=TrickRepository::class)
 * @UniqueEntity(
 *     fields={"name"},
 *     message="This trick already exists"
 * )
 */
class Trick implements JsonSerializable
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $name;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_date;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $last_updated_date;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="tricks")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="tricks")
     */
    private $category;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="trick", orphanRemoval=true)
     */
    private $comments;

    /**
     * @ORM\OneToMany(targetEntity=TrickPicture::class, mappedBy="trick", orphanRemoval=true, cascade={"persist"})
     */
    private $pictures;

    private $firstPicture;

    /**
     * @Assert\All({
     * @Assert\Image(mimeTypes="image/jpeg")
     * })
     */
    private $pictureFiles;

    /**
     * @ORM\OneToMany(targetEntity=TrickVideo::class, mappedBy="trick", orphanRemoval=true, cascade={"persist"})
     */
    private $trickVideos;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $mainPicture;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->pictures = new ArrayCollection();
        $this->trickVideos = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCreatedDate(): ?\DateTimeInterface
    {
        return $this->created_date;
    }

    public function setCreatedDate(\DateTimeInterface $created_date): self
    {
        $this->created_date = $created_date;

        return $this;
    }

    public function getLastUpdatedDate(): ?\DateTimeInterface
    {
        return $this->last_updated_date;
    }

    public function setLastUpdatedDate(?\DateTimeInterface $last_updated_date): self
    {
        $this->last_updated_date = $last_updated_date;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setTrick($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getTrick() === $this) {
                $comment->setTrick(null);
            }
        }

        return $this;
    }

    public function jsonSerialize()
    {
        return
            [
                'id'   => $this->getId(),
                'name' => $this->getName(),
                'created_date' => $this->getCreatedDate(),
                'last_updated_date' => $this->getCreatedDate(),
                'author' => $this->getAuthor(),
                'description' => $this->getDescription(),
                'category' => $this->getCategory(),
                'comments' => $this->getComments(),
                'firstPicture' => $this->getPictureFiles()
            ];
    }

    /**
     * @return Collection|TrickPicture[]
     */
    public function getPictures(): Collection
    {
        return $this->pictures;
    }

    public function addPicture(TrickPicture $picture): self
    {
        if (!$this->pictures->contains($picture)) {
            $this->pictures[] = $picture;
            $picture->setTrick($this);
        }

        return $this;
    }

    public function removePicture(TrickPicture $picture): self
    {
        if ($this->pictures->removeElement($picture)) {
            // set the owning side to null (unless already changed)
            if ($picture->getTrick() === $this) {
                $picture->setTrick(null);
            }
        }

        return $this;
    }

    /**
     * @return mixed
     */
    public function getPictureFiles()
    {
        return $this->pictureFiles;
    }

    /**
     * @param mixed $pictureFiles
     */
    public function setPictureFiles($pictureFiles): self
    {
        foreach ($pictureFiles as $file) {
            $picture = new TrickPicture();
            $picture->setPictureFile($file);
            $this->addPicture($picture);
        }
        $this->pictureFiles = $pictureFiles;
        return $this;
    }

    public function setFirstPicture()
    {
        if (!empty($this->pictures)) {
            $this->firstPicture = $this->pictures[0];
        }
        return $this;
    }

    public function getFirstPicture()
    {
        return $this->firstPicture;
    }

    /**
     * @return Collection|TrickVideo[]
     */
    public function getTrickVideos(): Collection
    {
        return $this->trickVideos;
    }

    public function addTrickVideo(TrickVideo $trickVideo): self
    {
        if (!$this->trickVideos->contains($trickVideo)) {
            $this->trickVideos[] = $trickVideo;
            $trickVideo->setTrick($this);
        }

        return $this;
    }

    public function removeTrickVideo(TrickVideo $trickVideo): self
    {
        if ($this->trickVideos->removeElement($trickVideo)) {
            // set the owning side to null (unless already changed)
            if ($trickVideo->getTrick() === $this) {
                $trickVideo->setTrick(null);
            }
        }

        return $this;
    }

    public function getMainPicture(): ?string
    {
        return $this->mainPicture;
    }

    public function setMainPicture(?string $mainPicture): self
    {
        $this->mainPicture = $mainPicture;

        return $this;
    }
}

src/Form/Tricks/TrickVideoType.php
<?php

namespace App\Form\Tricks;

use App\Entity\TrickVideo;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ButtonType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TrickVideoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('url', TextType::class, [
                'label' => false,
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => TrickVideo::class,
        ]);
    }
}

src/Controller/Tricks/DeleteTrickController.php
<?php


namespace App\Controller\Tricks;


use App\Entity\Trick;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Filesystem\Exception\IOExceptionInterface;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\Filesystem\Path;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Component\Routing\Annotation\Route;

class DeleteTrickController extends AbstractController
{
    /**
     * @Route("/trick_delete/{id}", name="trick_delete")
     */
    public function index(int $id): Response
    {
        $this->denyAccessUnlessGranted('ROLE_USER');
        $trick = $this->getDoctrine()
            ->getRepository(Trick::class)
            ->find($id);
        $entityManager = $this->getDoctrine()->getManager();
        if ($trick === null) {
            $this->addFlash('danger', 'An error occured ( ⚆ _ ⚆ )');
            return $this->redirectToRoute('app_homepage');
        }
        $entityManager->remove($trick);
        $entityManager->flush();
        $filesystem = new Filesystem();
        try {
            $trickPictureFolder = $this->getParameter('kernel.project_dir').'/public/uploads/tricks/'.$id;
            $filesystem->remove($trickPictureFolder);
        } catch (IOExceptionInterface $exception) {
            $this->addFlash("danger", "An error occurred while deleting the trick");
        }
        $this->addFlash('danger', 'Trick successfully deleted');
        return $this->redirectToRoute('app_homepage');
    }
}

src/Controller/Tricks/DeleteTrickPictureController.php
<?php

namespace App\Controller\Tricks;

use App\Entity\Trick;
use App\Entity\TrickPicture;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Filesystem\Exception\IOExceptionInterface;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class DeleteTrickPictureController extends AbstractController
{
    /**
     * @Route("/trick_picture_delete/{id}", name="trick_picture_delete")
     */
    public function deletePicture(Request $request, int $id): Response
    {
        $this->denyAccessUnlessGranted('ROLE_USER');
        $trickId = $request->get('trick_id');
        $trickPicture = $this->getDoctrine()
            ->getRepository(TrickPicture::class)
            ->find($id);
        $entityManager = $this->getDoctrine()->getManager();
        if ($trickPicture === null) {
            $this->addFlash('danger', 'An error occured ( ⚆ _ ⚆ )');
        } else {
            $entityManager->remove($trickPicture);
            $entityManager->flush();
            $filename = $request->get('filename');
            $filesystem = new Filesystem();
            try {
                $trickPicturePath = $this->getParameter('kernel.project_dir').'/public/uploads/tricks/'.$trickId.'/'.$filename;
                $filesystem->remove($trickPicturePath);
            } catch (IOExceptionInterface $exception) {
                $this->addFlash("danger", "An error occurred while deleting picture");
            }
            $this->addFlash('danger', 'Picture successfully deleted');
        }
        return $this->redirectToRoute('trick_update', ['id' => $trickId]);
    }

    /**
     * @Route("/trick_main_picture_delete/{id}", name="trick_main_picture_delete")
     */
    public function deleteMainPicture(Request $request, int $id): Response
    {
        $trick = $this->getDoctrine()
            ->getRepository(Trick::class)
            ->find($id);
        $entityManager = $this->getDoctrine()->getManager();
        if ($trick->getMainPicture() === null) {
            $this->addFlash('danger', 'An error occured ( ⚆ _ ⚆ )');
        } else {
            $filename = $trick->getMainPicture();
            $filesystem = new Filesystem();
            try {
                $trickPicturePath = $this->getParameter('kernel.project_dir').'/public/uploads/tricks/'.$id.'/'.$filename;
                $filesystem->remove($trickPicturePath);
            } catch (IOExceptionInterface $exception) {
                $this->addFlash("danger", "An error occurred while deleting picture");
            }
            $trick->setMainPicture(null);
            $entityManager->flush();
            $this->addFlash('danger', 'Picture successfully deleted');
        }
        return $this->redirectToRoute('trick_update', ['id' => $id]);
    }
}

src/Controller/Tricks/DeleteTrickVideoController.php
<?php


namespace App\Controller\Tricks;


use App\Entity\TrickVideo;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Filesystem\Exception\IOExceptionInterface;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class DeleteTrickVideoController extends AbstractController
{
    /**
     * @Route("/trick_video_delete/{id}", name="trick_video_delete")
     */
    public function deleteVideo(Request $request, int $id): Response
    {
        $this->denyAccessUnlessGranted('ROLE_USER');
        $trickId = $request->get('trick_id');
        $trickVideo = $this->getDoctrine()
            ->getRepository(TrickVideo::class)
            ->find($id);
        $entityManager = $this->getDoctrine()->getManager();
        if ($trickVideo === null) {
            $this->addFlash('danger', 'An error occured ( ⚆ _ ⚆ )');
        } else {
            $entityManager->remove($trickVideo);
            $entityManager->flush();
            $this->addFlash('danger', 'Video successfully deleted');
        }
        return $this->redirectToRoute('trick_update', ['id' => $trickId]);
    }
}

src/Controller/Tricks/EditTrickVideoController.php
<?php


namespace App\Controller\Tricks;


use App\Entity\TrickVideo;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class EditTrickVideoController extends AbstractController
{
    /**
     * @Route("/trick_video_edit/{id}", name="trick_video_edit")
     */
    public function editVideo(Request $request, int $id): Response
    {
        $this->denyAccessUnlessGranted('ROLE_USER');
        $trickId = $request->get('trick_id');
        $trickVideo = $this->getDoctrine()
            ->getRepository(TrickVideo::class)
            ->find($id);
        $entityManager = $this->getDoctrine()->getManager();
        if ($trickVideo === null) {
            $this->addFlash('danger', 'An error occured ( ⚆ _ ⚆ )');
        } else {
            $trickVideo->setUrl($request->get('trick_url'));
            $entityManager->flush();
            $this->addFlash('success', 'Video successfully edited');
        }
        return $this->redirectToRoute('trick_update', ['id' => $trickId]);
    }
}

templates/tricks/card.html.twig
<div class="col-lg-3 col-md-6 col-12 card_col">
    <div class="card mb-4 card_div">
            {% if mainPicture %}
                <div class="card_img_top_div" style="background-image: url('{{ asset('uploads/tricks/' ~ id ~ '/' ~ mainPicture) }}')"></div>
            {% elseif firstPicture %}

                <div class="card_img_top_div" style="background-image: url('{{ asset('uploads/tricks/' ~ id ~ '/' ~ firstPicture.filename) }}')"></div>

            {% else %}
                <div class="card_img_top_div" style="background-image: url('{{ asset('media/icon.jpg') }}')"></div>
            {% endif %}

        <div class="card-body">
            <h5 class="card-title"><a class="nav-link cool_font card_title_link" href="{{ path('trick_display', {id: id} ) }}">{{ name }}</a>
                <!-- Button trigger modal -->
                <a data-bs-toggle="modal" data-bs-target="#confirmDeleteModal">

                </a>
            </h5>
            <p class="card-text">{{ description }}</p>
        </div>
        {% if is_granted('IS_AUTHENTICATED_FULLY') %}
            <div class="edit_delete_block">
                <a class="nav-link edit_trick_btn" href="{{ path('trick_update', {id: id} ) }}">&#9998;</a>
                <form id="trick_card_form_delete" method="post" action="{{ path('trick_delete', {id: id} ) }}" onsubmit="return confirm('Are you sure you want to delete this trick ?')">
                    <input type="hidden" name="_method" value="DELETE">
                    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ id) }}">
                    <input type="image" src="{{ asset('media/bin_s.png') }}" />
                </form>
            </div>
        {% endif %}
    </div>
</div>
{% if is_granted('IS_AUTHENTICATED_FULLY') %}

{% endif %}

templates/tricks/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {% if hideImg == 0 %}
        <div class="homepage_image_div" style="background-image: url('{{ asset('media/SnowboardTrick_mainImage.jpg') }}')">
        </div>
        <div class="scroll_down_div">
            <a class="scroll_down_arrow" href="#tricks_block">&#10534;</a>
        </div>
    {% endif %}

    {% if is_granted('IS_AUTHENTICATED_FULLY') %}
        <p class="text-right" id="add_new_trick_p">
            <a class="nav-link" id="add_new_trick_a" href="{{ path('new_trick') }}">Add New&#43;</a>
        </p>
    {% endif %}
    <div id="tricks_block">
        {% for trick in tricks %}
            {% if loop.index == 1 or loop.index%5 == 0 %}
                <div class="row justify-content-center trick_row">
            {% endif %}
                {% set mainPicture = '' %}
                {% if mainPicture and mainPicture is not null %}
                    {% set mainPicture = mainPicture %}
                {% endif %}
                {% set firstPicture = '' %}
                {% if trick.pictures and trick.pictures|first is not null %}
                    {% if trick.firstPicture is not null %}
                        {% set firstPicture = trick.pictures|first %}
                    {% endif %}
                {% endif %}
                {% set delete_id = trick.id %}
                {%
                    include 'tricks/card.html.twig'
                    with {
                        'id': trick.id,
                        'delete_id': delete_id,
                        'name': trick.name,
                        'description': trick.description,
                        'picture': firstPicture,
                        'mainPicture': mainPicture
                    }
                %}
            {% if loop.index%4 == 0 %}
                </div>
            {% endif %}
        {% endfor %}
    </div>
    <div class="text-center mb-4">
        <button type="button" class="btn btn-dark" id="loadMoreTricksBtn">Load More</button>
    </div>
    <input id="pageType" type="hidden" value="trick_index">

{% endblock %}

templates/tricks/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Register{% endblock %}

{% block body %}
<h1 class="mt-4 text-center cool_font">New trick</h1>
<div class="container text-center mt-4 mb-4">
    {{ form_start(newTrickForm) }}
    <div class="row mt-2">
        {{ form_row(newTrickForm.name) }}
    </div>
    <div class="row mt-2">
        {{ form_row(newTrickForm.description) }}
    </div>
    <div class="row mt-2 justify-content-center">
        Category
    </div>
    <div class="row">
        {{ form_row(newTrickForm.category) }}
    </div>
    <div class="row mt-2 justify-content-center">
        Main Picture
    </div>
    <div class="row">
        {{ form_row(newTrickForm.mainPicture) }}
    </div>
    <div class="row mt-2 justify-content-center">
        Picture(s)
    </div>
    <div class="row">
        {{ form_row(newTrickForm.pictureFiles) }}
    </div>
    <div class="row mt-2 justify-content-center">
        Video(s) url
    </div>
    {% for video in newTrickForm.trickVideos %}
        <div class="row">
            {{ form_row(video.url) }}
        </div>
    {% endfor %}



    <ul class="trickVideos trickVideosUl"
        data-index="{{ newTrickForm.trickVideos|length > 0 ? newTrickForm.trickVideos|last.vars.name + 1 : 0 }}"
        data-prototype="{{ form_widget(newTrickForm.trickVideos.vars.prototype)|e('html_attr') }}"
    ></ul>

    <button type="button" id="add_input" class="add_item_link" data-collection-holder-class="trickVideos">Add a video url</button>

    {{ form_end(newTrickForm) }}
</div>
    <input id="pageType" type="hidden" value="trick_new">
{% endblock %}

templates/tricks/one.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <div class="container mt-4 mb-2 text-center">
        {% if trick.mainPicture is not null %}
            <img id="trick_main_picture" src="{{ asset('uploads/tricks/' ~ trick.id ~ '/' ~ trick.mainPicture) }}" alt="" width="400">
        {% else %}
            <img id="trick_main_picture" src="{{ asset('media/icon.jpg') }}" alt="" width="400">
        {% endif %}
    </div>

    <h1 class="text-center cool_font">{{ trick.name }}</h1>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-6 trick_detail_left_col">
                Author :
            </div>
            <div class="col-6 justify-content-end">
                {{ trick.author.username}} &#183; {{ trick.createdDate |format_datetime(locale='en') }}
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-6 trick_detail_left_col">
                Category :
            </div>
            <div class="col-6">
                {{ trick.category.name }}
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-6 trick_detail_left_col">
                Description :
            </div>
            <div class="col-6">
                {{ trick.description }}
            </div>
        </div>
    </div>

    {% if trick.pictures|length > 0 %}
        <div class="container mt-4">
            <div class="row">
            {% for picture in trick.pictures %}
                <div class="col-lg-3 col-md-6 col-12 p-1">
                    <img src="{{ asset('uploads/tricks/' ~ trick.id ~ '/' ~ picture.filename) }}" width="100%" height="200px">
                </div>
            {% endfor %}
            </div>
        </div>
    {% endif %}
    {% if trick.trickVideos|length > 0 %}
        <div class="container mt-4">
            <div class="row">
                {% for video in trick.trickVideos %}
                    <div class="col-lg-3 col-md-6 col-12 p-1">
                        {{ video.urlFrame | raw }}
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endif %}

    <h2 class="text-center cool_font">Comments</h2>
    {% if is_granted('IS_AUTHENTICATED_FULLY') %}
        <div class="container text-center">
                {{ form_start(addCommentForm) }}
                {{ form_end(addCommentForm) }}
        </div>
    {% endif %}

    <div class="text-center" id="comment_block">
    {% for comment in comments %}
        <p>[{{ comment.createdDate|date("j/n/Y H:i:s", "Europe/Paris") }}] {{ comment.author.username }}
            {% if comment.authorIconPath is not null %}
                <img id="" src="{{ asset('uploads/users/' ~ comment.authorIconPath) }}" alt="" width="25">
            {% else %}
                <img id="" src="https://ocrp6.s3.eu-west-3.amazonaws.com/user_icon.png" alt="" width="25">
            {% endif %}
        </p>
        <p>{{ comment.content }}</p>
    {% endfor %}
    </div>
    <div class="container text-center mb-4">
        <button type="button" class="btn btn-dark" id="loadMoreCommentsBtn">Load More</button>
    </div>
    {% if comments|length > 1 %}
    {% endif %}
    <input id="trickId" type="hidden" value="{{ trick.id }}">
    <input id="pageType" type="hidden" value="trick_1">
{% endblock %}